/* Heroa.java */
/* Generated By:JavaCC: Do not edit this line. Heroa.java */
import java.io.*;
import java.util.*;

public class Heroa implements HeroaConstants {

    static int totalErrores = 0;

    public static void main(String[] args) {
        String archivo = "";
        try {
            Scanner sc = new Scanner(System.in);
            System.out.print("Ingrese el nombre del archivo a analizar: ");
            archivo = sc.nextLine();
            InputStream input = new FileInputStream(archivo);
            sc.close();
            Heroa analizador = new Heroa(input);
            analizador.Programa();

            System.out.println("\n--- An\u00e1lisis finalizado: " + totalErrores + " error(es) encontrado(s). ---");

        } catch (FileNotFoundException e) {
            System.out.println("Error: El archivo '" + archivo + "' no existe.");
        } catch (ParseException e) {
            int linea = (e.currentToken != null && e.currentToken.next != null)
                        ? e.currentToken.next.beginLine : -1;
            System.out.println("Error Sint\u00e1ctico | L\u00ednea " + linea
                + " [global]: token inesperado '" + e.currentToken.next.image + "'");
            totalErrores++;
        } catch (TokenMgrError e) {
            System.out.println("Error L\u00e9xico grave: " + e.getMessage());
            totalErrores++;
        }
    }

  static void reporteErrores(ParseException e, String regla) throws ParseException {Token t = e.currentToken.next;
    if (t.kind != ERROR_LEXICO) {
        StringBuilder sugerencia = new StringBuilder();
        boolean esperaTipoDato = false;
        boolean esperaPrincipal = false;
        for (int i = 0; i < e.expectedTokenSequences.length; i++) {
            for (int j = 0; j < e.expectedTokenSequences[i].length; j++) {
                int tokenId = e.expectedTokenSequences[i][j];
                String esperado = e.tokenImage[tokenId];
                if (sugerencia.indexOf(esperado) < 0) {
                    sugerencia.append(esperado).append(" ");
                }
                if (tokenId == ENTERO || tokenId == DECIMAL || tokenId == CHAR
                        || tokenId == BOOLEANO || tokenId == CADENA) {
                    esperaTipoDato = true;
                } else if (tokenId == PRINCIPAL) {
                    esperaPrincipal = true;
                }
            }
        }
        String mensaje;
        if (esperaPrincipal) {
            mensaje = "el programa debe comenzar con la palabra reservada 'principal'.";
        } else if (esperaTipoDato) {
            mensaje = "se esperaba un tipo de dato (entero, decimal, caracter, booleano, cadena).";
        } else {
            mensaje = "se esperaba " + sugerencia.toString().trim() + " despu\u00e9s de este token.";
        }
        System.out.println("Error en linea " + t.beginLine
            + ", columna " + t.beginColumn
            + " [Sint\u00e1ctico]: error en el token '" + t.image
            + "'; " + mensaje);

        Heroa.totalErrores++;
    }
    int balanceLlaves = 0;

    while (true) {
        Token tok = getToken(1);
        if (tok.kind == EOF) break;

        if (tok.kind == LLAVE_ABRE) {
            balanceLlaves++;
        } else if (tok.kind == LLAVE_CIERRA) {
            if (balanceLlaves > 0) {
                balanceLlaves--;
            } else {
                break;
            }
        } else if (balanceLlaves == 0
                && (tok.kind == DELIMITADOR || esTokenDeSincronizacion(tok))) {
            break;
        }
        getNextToken();
        if (tok.kind == LLAVE_CIERRA && balanceLlaves == 0) {
            break;
        }
    }
    if (getToken(1).kind == DELIMITADOR) {
        getNextToken();
    }
  }

  static boolean esTokenDeSincronizacion(Token t) throws ParseException {return t.kind == VARIABLE   || t.kind == CONSTANTE  ||
           t.kind == SI         || t.kind == SINO       ||
           t.kind == SINO_SI    || t.kind == MIENTRAS   ||
           t.kind == PARA       || t.kind == HACER      ||
           t.kind == FUNCION    || t.kind == IMPRIMIR   ||
           t.kind == LEER       || t.kind == ROMPER     ||
           t.kind == CONTINUAR;
  }

// ═════════════════════════════════════════════
//  GRAMÁTICA
// ═════════════════════════════════════════════
  static final public 
void Programa() throws ParseException {
    try {
      Principal();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNCION:{
        ListaFunciones();
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        ;
      }
      jj_consume_token(0);
    } catch (ParseException e) {
reporteErrores(e, "Global");
        Token t = getToken(1);
        while (t.kind != FUNCION && t.kind != EOF) {
            getNextToken();
            t = getToken(1);
        }
        if (t.kind == FUNCION) {
            ListaFunciones();
        }
    }
}

  static final public void Principal() throws ParseException {
    jj_consume_token(PRINCIPAL);
    jj_consume_token(LLAVE_ABRE);
    ListaSentencias();
    jj_consume_token(LLAVE_CIERRA);
}

  static final public void ListaSentencias() throws ParseException {
    Sentencia();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SI:
    case SINO:
    case SINO_SI:
    case MIENTRAS:
    case PARA:
    case HACER:
    case ROMPER:
    case CONTINUAR:
    case VARIABLE:
    case CONSTANTE:
    case IMPRIMIR:
    case ID_VARIABLE:{
      ListaSentencias();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      ;
    }
}

  static final public void ListaFunciones() throws ParseException {
    DefFuncion();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case FUNCION:{
      ListaFunciones();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
}

  static final public void Sentencia() throws ParseException {
    try {
      if (jj_2_1(3)) {
        DeclaracionArregloMatriz();
      } else if (jj_2_2(3)) {
        Declaracion();
      } else if (jj_2_3(3)) {
        AsignacionArregloMatriz();
      } else if (jj_2_4(2)) {
        Asignacion();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SI:
        case MIENTRAS:
        case PARA:
        case HACER:{
          EstructuraControl();
          break;
          }
        case ID_VARIABLE:{
          LlamadaFuncion();
          break;
          }
        case IMPRIMIR:{
          Imprimir();
          break;
          }
        case ROMPER:
        case CONTINUAR:{
          SentenciasSaltos();
          break;
          }
        case SINO:
        case SINO_SI:{
          OrfandadSino();
          break;
          }
        default:
          jj_la1[3] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (ParseException e) {
reporteErrores(e, "Sentencia");
    }
}

  static final public void OrfandadSino() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SINO_SI:{
      t = jj_consume_token(SINO_SI);
      jj_consume_token(PAREN_ABRE);
      Condicion();
      jj_consume_token(PAREN_CIERRA);
      jj_consume_token(LLAVE_ABRE);
      ListaSentencias();
      jj_consume_token(LLAVE_CIERRA);
      break;
      }
    case SINO:{
      t = jj_consume_token(SINO);
      jj_consume_token(LLAVE_ABRE);
      ListaSentencias();
      jj_consume_token(LLAVE_CIERRA);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
System.out.println("Error en linea " + t.beginLine
            + ", columna " + t.beginColumn
            + " [Sint\u00e1ctico]: error en el token '" + t.image
            + "'; se encontr\u00f3 una estructura condicional incompleta (falta el bloque 'si' previo).");
        Heroa.totalErrores++;
}

// ─────────────────────────────────────────────
//  DECLARACIONES Y ASIGNACIONES
// ─────────────────────────────────────────────
  static final public 
void TipoDato() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ENTERO:{
      jj_consume_token(ENTERO);
      break;
      }
    case DECIMAL:{
      jj_consume_token(DECIMAL);
      break;
      }
    case CHAR:{
      jj_consume_token(CHAR);
      break;
      }
    case BOOLEANO:{
      jj_consume_token(BOOLEANO);
      break;
      }
    case CADENA:{
      jj_consume_token(CADENA);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void Declaracion() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case CONSTANTE:{
      jj_consume_token(CONSTANTE);
      TipoDato();
      jj_consume_token(ID_CONSTANTE);
      jj_consume_token(ASIGNACION);
      Valor();
      jj_consume_token(DELIMITADOR);
      break;
      }
    case VARIABLE:{
      jj_consume_token(VARIABLE);
      TipoDato();
      if (jj_2_5(2)) {
        jj_consume_token(ID_VARIABLE);
        jj_consume_token(ASIGNACION);
        Valor();
        jj_consume_token(DELIMITADOR);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ID_VARIABLE:{
          ListaIdsVariables();
          jj_consume_token(DELIMITADOR);
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void ListaIdsVariables() throws ParseException {
    jj_consume_token(ID_VARIABLE);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COMA:{
      jj_consume_token(COMA);
      ListaIdsVariables();
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
}

  static final public void Asignacion() throws ParseException {
    jj_consume_token(ID_VARIABLE);
    OperadorAsignacion();
    Valor();
    jj_consume_token(DELIMITADOR);
}

  static final public void OperadorAsignacion() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASIGNACION:{
      jj_consume_token(ASIGNACION);
      break;
      }
    case ASIGNACION_MULTIPLICACION:{
      jj_consume_token(ASIGNACION_MULTIPLICACION);
      break;
      }
    case ASIGNACION_DIVISION:{
      jj_consume_token(ASIGNACION_DIVISION);
      break;
      }
    case ASIGNACION_MODULO:{
      jj_consume_token(ASIGNACION_MODULO);
      break;
      }
    case ASIGNACION_SUMA:{
      jj_consume_token(ASIGNACION_SUMA);
      break;
      }
    case ASIGNACION_RESTA:{
      jj_consume_token(ASIGNACION_RESTA);
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

// ─────────────────────────────────────────────
//  EXPRESIONES
// ─────────────────────────────────────────────
  static final public 
void Valor() throws ParseException {
    ExpLogica();
}

  static final public void ExpLogica() throws ParseException {
    TerminoLogico();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_1;
      }
      jj_consume_token(OR);
      TerminoLogico();
    }
}

  static final public void TerminoLogico() throws ParseException {
    FactorLogico();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_2;
      }
      jj_consume_token(AND);
      FactorLogico();
    }
}

  static final public void FactorLogico() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NOT:{
      jj_consume_token(NOT);
      FactorLogico();
      break;
      }
    case VERDADERO:
    case FALSO:
    case LEER:
    case PAREN_ABRE:
    case ID_VARIABLE:
    case ID_CONSTANTE:
    case VALOR_CADENA:
    case VALOR_CHAR:
    case VALOR_NUMERO:{
      ExpRelacional();
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void ExpRelacional() throws ParseException {
    ExpAritmetica();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IGUAL_QUE:
    case DIFERENTE_DE:
    case MAYOR_IGUAL:
    case MENOR_IGUAL:
    case MAYOR_QUE:
    case MENOR_QUE:{
      OperadorRelacional();
      ExpAritmetica();
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      ;
    }
}

  static final public void OperadorRelacional() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IGUAL_QUE:{
      jj_consume_token(IGUAL_QUE);
      break;
      }
    case DIFERENTE_DE:{
      jj_consume_token(DIFERENTE_DE);
      break;
      }
    case MAYOR_QUE:{
      jj_consume_token(MAYOR_QUE);
      break;
      }
    case MENOR_QUE:{
      jj_consume_token(MENOR_QUE);
      break;
      }
    case MAYOR_IGUAL:{
      jj_consume_token(MAYOR_IGUAL);
      break;
      }
    case MENOR_IGUAL:{
      jj_consume_token(MENOR_IGUAL);
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void ExpAritmetica() throws ParseException {
    TerminoAritmetico();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SUMA:
      case RESTA:{
        ;
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SUMA:{
        jj_consume_token(SUMA);
        break;
        }
      case RESTA:{
        jj_consume_token(RESTA);
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      TerminoAritmetico();
    }
}

  static final public void TerminoAritmetico() throws ParseException {
    Potencia();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICACION:
      case DIVISION:
      case MODULO:{
        ;
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICACION:{
        jj_consume_token(MULTIPLICACION);
        break;
        }
      case DIVISION:{
        jj_consume_token(DIVISION);
        break;
        }
      case MODULO:{
        jj_consume_token(MODULO);
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Potencia();
    }
}

  static final public void Potencia() throws ParseException {
    Atomo();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case POTENCIA:{
      jj_consume_token(POTENCIA);
      Potencia();
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      ;
    }
}

  static final public void Atomo() throws ParseException {
    if (jj_2_6(2147483647)) {
      AccesoMatriz();
    } else if (jj_2_7(2147483647)) {
      AccesoArreglo();
    } else if (jj_2_8(2147483647)) {
      LlamadaFuncionInterna();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ID_VARIABLE:{
        jj_consume_token(ID_VARIABLE);
        break;
        }
      case ID_CONSTANTE:{
        jj_consume_token(ID_CONSTANTE);
        break;
        }
      case VERDADERO:
      case FALSO:
      case VALOR_CADENA:
      case VALOR_CHAR:
      case VALOR_NUMERO:{
        ValorVariable();
        break;
        }
      case LEER:{
        Leer();
        break;
        }
      case PAREN_ABRE:{
        jj_consume_token(PAREN_ABRE);
        ExpAritmetica();
        jj_consume_token(PAREN_CIERRA);
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  static final public void ValorVariable() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VALOR_NUMERO:{
      jj_consume_token(VALOR_NUMERO);
      break;
      }
    case VALOR_CADENA:{
      jj_consume_token(VALOR_CADENA);
      break;
      }
    case VALOR_CHAR:{
      jj_consume_token(VALOR_CHAR);
      break;
      }
    case VERDADERO:{
      jj_consume_token(VERDADERO);
      break;
      }
    case FALSO:{
      jj_consume_token(FALSO);
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

// ─────────────────────────────────────────────
//  ESTRUCTURAS DE CONTROL
// ─────────────────────────────────────────────
  static final public 
void EstructuraControl() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SI:{
      Condicionales();
      break;
      }
    case MIENTRAS:
    case PARA:
    case HACER:{
      Ciclos();
      break;
      }
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

// ─────────────────────────────────────────────
//  CONDICIONALES
// ─────────────────────────────────────────────
  static final public 
void Condicionales() throws ParseException {
    jj_consume_token(SI);
    jj_consume_token(PAREN_ABRE);
    Condicion();
    jj_consume_token(PAREN_CIERRA);
    jj_consume_token(LLAVE_ABRE);
    ListaSentencias();
    jj_consume_token(LLAVE_CIERRA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SINO:
    case SINO_SI:{
      BloqueSino();
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      ;
    }
}

  static final public void BloqueSino() throws ParseException {
    if (jj_2_9(2)) {
      ListaSinoSi();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SINO:{
        OpcionSinoFinal();
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        ;
      }
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SINO:{
        OpcionSinoFinal();
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  static final public void ListaSinoSi() throws ParseException {
    jj_consume_token(SINO_SI);
    jj_consume_token(PAREN_ABRE);
    Condicion();
    jj_consume_token(PAREN_CIERRA);
    jj_consume_token(LLAVE_ABRE);
    ListaSentencias();
    jj_consume_token(LLAVE_CIERRA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SINO_SI:{
      ListaSinoSi();
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      ;
    }
}

  static final public void OpcionSinoFinal() throws ParseException {
    jj_consume_token(SINO);
    jj_consume_token(LLAVE_ABRE);
    ListaSentencias();
    jj_consume_token(LLAVE_CIERRA);
}

  static final public void Condicion() throws ParseException {
    ExpLogica();
}

// ─────────────────────────────────────────────
//  CICLOS
// ─────────────────────────────────────────────
  static final public 
void Ciclos() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MIENTRAS:{
      Mientras();
      break;
      }
    case HACER:{
      HacerMientras();
      break;
      }
    case PARA:{
      Para();
      break;
      }
    default:
      jj_la1[27] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void Para() throws ParseException {
    jj_consume_token(PARA);
    jj_consume_token(PAREN_ABRE);
    AsignacionPara();
    jj_consume_token(DELIMITADOR);
    Condicion();
    jj_consume_token(DELIMITADOR);
    Actualizacion();
    jj_consume_token(PAREN_CIERRA);
    jj_consume_token(LLAVE_ABRE);
    ListaSentencias();
    jj_consume_token(LLAVE_CIERRA);
}

  static final public void AsignacionPara() throws ParseException {
    jj_consume_token(VARIABLE);
    TipoDato();
    jj_consume_token(ID_VARIABLE);
    jj_consume_token(ASIGNACION);
    Valor();
}

  static final public void Actualizacion() throws ParseException {
    jj_consume_token(ID_VARIABLE);
    OperadorAsignacionAritmetico();
    Valor();
}

  static final public void OperadorAsignacionAritmetico() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASIGNACION_MULTIPLICACION:{
      jj_consume_token(ASIGNACION_MULTIPLICACION);
      break;
      }
    case ASIGNACION_DIVISION:{
      jj_consume_token(ASIGNACION_DIVISION);
      break;
      }
    case ASIGNACION_SUMA:{
      jj_consume_token(ASIGNACION_SUMA);
      break;
      }
    case ASIGNACION_RESTA:{
      jj_consume_token(ASIGNACION_RESTA);
      break;
      }
    case ASIGNACION_MODULO:{
      jj_consume_token(ASIGNACION_MODULO);
      break;
      }
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void Mientras() throws ParseException {
    jj_consume_token(MIENTRAS);
    jj_consume_token(PAREN_ABRE);
    Condicion();
    jj_consume_token(PAREN_CIERRA);
    jj_consume_token(LLAVE_ABRE);
    ListaSentencias();
    jj_consume_token(LLAVE_CIERRA);
}

  static final public void HacerMientras() throws ParseException {
    jj_consume_token(HACER);
    jj_consume_token(LLAVE_ABRE);
    ListaSentencias();
    jj_consume_token(LLAVE_CIERRA);
    jj_consume_token(MIENTRAS);
    jj_consume_token(PAREN_ABRE);
    Condicion();
    jj_consume_token(PAREN_CIERRA);
    jj_consume_token(DELIMITADOR);
}

  static final public void SentenciasSaltos() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ROMPER:{
      jj_consume_token(ROMPER);
      break;
      }
    case CONTINUAR:{
      jj_consume_token(CONTINUAR);
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(DELIMITADOR);
}

// ─────────────────────────────────────────────
//  FUNCIONES
// ─────────────────────────────────────────────
  static final public 
void DefFuncion() throws ParseException {
    jj_consume_token(FUNCION);
    jj_consume_token(ID_VARIABLE);
    jj_consume_token(PAREN_ABRE);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ENTERO:
    case DECIMAL:
    case CHAR:
    case BOOLEANO:
    case CADENA:{
      ListaParametros();
      break;
      }
    default:
      jj_la1[30] = jj_gen;
      ;
    }
    jj_consume_token(PAREN_CIERRA);
    jj_consume_token(LLAVE_ABRE);
    SentenciasFuncion();
    jj_consume_token(LLAVE_CIERRA);
}

  static final public void ListaParametros() throws ParseException {
    TipoDato();
    jj_consume_token(ID_VARIABLE);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COMA:{
      jj_consume_token(COMA);
      ListaParametros();
      break;
      }
    default:
      jj_la1[31] = jj_gen;
      ;
    }
}

  static final public void SentenciasFuncion() throws ParseException {
    if (jj_2_10(2)) {
      ListaSentencias();
    } else {
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RETORNAR:{
      Retorno();
      break;
      }
    default:
      jj_la1[32] = jj_gen;
      ;
    }
}

  static final public void Retorno() throws ParseException {
    jj_consume_token(RETORNAR);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VERDADERO:
    case FALSO:
    case LEER:
    case NOT:
    case PAREN_ABRE:
    case ID_VARIABLE:
    case ID_CONSTANTE:
    case VALOR_CADENA:
    case VALOR_CHAR:
    case VALOR_NUMERO:{
      Valor();
      break;
      }
    default:
      jj_la1[33] = jj_gen;
      ;
    }
    jj_consume_token(DELIMITADOR);
}

  static final public void LlamadaFuncion() throws ParseException {
    jj_consume_token(ID_VARIABLE);
    jj_consume_token(PAREN_ABRE);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VERDADERO:
    case FALSO:
    case LEER:
    case NOT:
    case PAREN_ABRE:
    case ID_VARIABLE:
    case ID_CONSTANTE:
    case VALOR_CADENA:
    case VALOR_CHAR:
    case VALOR_NUMERO:{
      ListaArgumentos();
      break;
      }
    default:
      jj_la1[34] = jj_gen;
      ;
    }
    jj_consume_token(PAREN_CIERRA);
    jj_consume_token(DELIMITADOR);
}

  static final public void LlamadaFuncionInterna() throws ParseException {
    jj_consume_token(ID_VARIABLE);
    jj_consume_token(PAREN_ABRE);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VERDADERO:
    case FALSO:
    case LEER:
    case NOT:
    case PAREN_ABRE:
    case ID_VARIABLE:
    case ID_CONSTANTE:
    case VALOR_CADENA:
    case VALOR_CHAR:
    case VALOR_NUMERO:{
      ListaArgumentos();
      break;
      }
    default:
      jj_la1[35] = jj_gen;
      ;
    }
    jj_consume_token(PAREN_CIERRA);
}

  static final public void ListaArgumentos() throws ParseException {
    Valor();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COMA:{
      jj_consume_token(COMA);
      ListaArgumentos();
      break;
      }
    default:
      jj_la1[36] = jj_gen;
      ;
    }
}

// ─────────────────────────────────────────────
//  ENTRADA Y SALIDA
// ─────────────────────────────────────────────
  static final public 
void Imprimir() throws ParseException {
    jj_consume_token(IMPRIMIR);
    jj_consume_token(PAREN_ABRE);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VERDADERO:
    case FALSO:
    case LEER:
    case NOT:
    case PAREN_ABRE:
    case ID_VARIABLE:
    case ID_CONSTANTE:
    case VALOR_CADENA:
    case VALOR_CHAR:
    case VALOR_NUMERO:{
      Valor();
      break;
      }
    default:
      jj_la1[37] = jj_gen;
      ;
    }
    jj_consume_token(PAREN_CIERRA);
    jj_consume_token(DELIMITADOR);
}

  static final public void Leer() throws ParseException {
    jj_consume_token(LEER);
    jj_consume_token(PAREN_ABRE);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VALOR_CADENA:{
      jj_consume_token(VALOR_CADENA);
      break;
      }
    default:
      jj_la1[38] = jj_gen;
      ;
    }
    jj_consume_token(PAREN_CIERRA);
}

// ─────────────────────────────────────────────
//  ARREGLOS Y MATRICES
// ─────────────────────────────────────────────
  static final public 
void DeclaracionArregloMatriz() throws ParseException {
    jj_consume_token(VARIABLE);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ARREGLO:{
      jj_consume_token(ARREGLO);
      TipoDato();
      jj_consume_token(ID_VARIABLE);
      jj_consume_token(CORCHETE_ABRE);
      jj_consume_token(VALOR_NUMERO);
      jj_consume_token(CORCHETE_CIERRA);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ASIGNACION:{
        jj_consume_token(ASIGNACION);
        jj_consume_token(LLAVE_ABRE);
        ListaValores();
        jj_consume_token(LLAVE_CIERRA);
        break;
        }
      default:
        jj_la1[39] = jj_gen;
        ;
      }
      break;
      }
    case MATRIX:{
      jj_consume_token(MATRIX);
      TipoDato();
      jj_consume_token(ID_VARIABLE);
      jj_consume_token(CORCHETE_ABRE);
      jj_consume_token(VALOR_NUMERO);
      jj_consume_token(CORCHETE_CIERRA);
      jj_consume_token(CORCHETE_ABRE);
      jj_consume_token(VALOR_NUMERO);
      jj_consume_token(CORCHETE_CIERRA);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ASIGNACION:{
        jj_consume_token(ASIGNACION);
        jj_consume_token(LLAVE_ABRE);
        ListaFilas();
        jj_consume_token(LLAVE_CIERRA);
        break;
        }
      default:
        jj_la1[40] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[41] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(DELIMITADOR);
}

  static final public void AccesoArreglo() throws ParseException {
    jj_consume_token(ID_VARIABLE);
    jj_consume_token(CORCHETE_ABRE);
    Indice();
    jj_consume_token(CORCHETE_CIERRA);
}

  static final public void AccesoMatriz() throws ParseException {
    jj_consume_token(ID_VARIABLE);
    jj_consume_token(CORCHETE_ABRE);
    Indice();
    jj_consume_token(CORCHETE_CIERRA);
    jj_consume_token(CORCHETE_ABRE);
    Indice();
    jj_consume_token(CORCHETE_CIERRA);
}

  static final public void AsignacionArregloMatriz() throws ParseException {
    if (jj_2_11(2147483647)) {
      AccesoMatriz();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ID_VARIABLE:{
        AccesoArreglo();
        break;
        }
      default:
        jj_la1[42] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(ASIGNACION);
    Valor();
    jj_consume_token(DELIMITADOR);
}

  static final public void Indice() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VALOR_NUMERO:{
      jj_consume_token(VALOR_NUMERO);
      break;
      }
    case ID_VARIABLE:{
      jj_consume_token(ID_VARIABLE);
      break;
      }
    default:
      jj_la1[43] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void ListaValores() throws ParseException {
    ValorVariable();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COMA:{
      jj_consume_token(COMA);
      ListaValores();
      break;
      }
    default:
      jj_la1[44] = jj_gen;
      ;
    }
}

  static final public void ListaFilas() throws ParseException {
    jj_consume_token(LLAVE_ABRE);
    ListaValores();
    jj_consume_token(LLAVE_CIERRA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COMA:{
      jj_consume_token(COMA);
      ListaFilas();
      break;
      }
    default:
      jj_la1[45] = jj_gen;
      ;
    }
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_9()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_10()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_11()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_3R_TerminoAritmetico_374_5_62()
 {
    if (jj_3R_Potencia_379_5_65()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_TerminoAritmetico_374_17_66()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_DeclaracionArregloMatriz_564_5_5()
 {
    if (jj_scan_token(VARIABLE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_DeclaracionArregloMatriz_566_9_14()) {
    jj_scanpos = xsp;
    if (jj_3R_DeclaracionArregloMatriz_570_9_15()) return true;
    }
    return false;
  }

  static private boolean jj_3R_ExpRelacional_354_22_61()
 {
    if (jj_3R_OperadorRelacional_359_5_64()) return true;
    if (jj_3R_ExpAritmetica_369_5_60()) return true;
    return false;
  }

  static private boolean jj_3R_LlamadaFuncionInterna_536_31_22()
 {
    if (jj_3R_ListaArgumentos_541_5_26()) return true;
    return false;
  }

  static private boolean jj_3R_ExpAritmetica_369_5_60()
 {
    if (jj_3R_TerminoAritmetico_374_5_62()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_ExpAritmetica_369_26_63()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Leer_555_5_76()
 {
    if (jj_scan_token(LEER)) return true;
    if (jj_scan_token(PAREN_ABRE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(71)) jj_scanpos = xsp;
    if (jj_scan_token(PAREN_CIERRA)) return true;
    return false;
  }

  static private boolean jj_3R_OperadorRelacional_359_5_64()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(36)) {
    jj_scanpos = xsp;
    if (jj_scan_token(37)) {
    jj_scanpos = xsp;
    if (jj_scan_token(45)) {
    jj_scanpos = xsp;
    if (jj_scan_token(46)) {
    jj_scanpos = xsp;
    if (jj_scan_token(38)) {
    jj_scanpos = xsp;
    if (jj_scan_token(39)) return true;
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_ListaArgumentos_541_14_34()
 {
    if (jj_scan_token(COMA)) return true;
    if (jj_3R_ListaArgumentos_541_5_26()) return true;
    return false;
  }

  static private boolean jj_3R_Imprimir_550_5_37()
 {
    if (jj_scan_token(IMPRIMIR)) return true;
    if (jj_scan_token(PAREN_ABRE)) return true;
    return false;
  }

  static private boolean jj_3R_TerminoLogico_342_21_50()
 {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_FactorLogico_347_5_49()) return true;
    return false;
  }

  static private boolean jj_3R_ExpRelacional_354_5_59()
 {
    if (jj_3R_ExpAritmetica_369_5_60()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_ExpRelacional_354_22_61()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_ExpLogica_337_21_46()
 {
    if (jj_scan_token(OR)) return true;
    if (jj_3R_TerminoLogico_342_5_45()) return true;
    return false;
  }

  static private boolean jj_3R_ListaArgumentos_541_5_26()
 {
    if (jj_3R_Valor_332_5_33()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_ListaArgumentos_541_14_34()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_FactorLogico_349_5_55()
 {
    if (jj_3R_ExpRelacional_354_5_59()) return true;
    return false;
  }

  static private boolean jj_3R_FactorLogico_347_5_49()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_FactorLogico_347_5_54()) {
    jj_scanpos = xsp;
    if (jj_3R_FactorLogico_349_5_55()) return true;
    }
    return false;
  }

  static private boolean jj_3R_FactorLogico_347_5_54()
 {
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_FactorLogico_347_5_49()) return true;
    return false;
  }

  static private boolean jj_3R_LlamadaFuncionInterna_536_5_11()
 {
    if (jj_scan_token(ID_VARIABLE)) return true;
    if (jj_scan_token(PAREN_ABRE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_LlamadaFuncionInterna_536_31_22()) jj_scanpos = xsp;
    if (jj_scan_token(PAREN_CIERRA)) return true;
    return false;
  }

  static private boolean jj_3R_TerminoLogico_342_5_45()
 {
    if (jj_3R_FactorLogico_347_5_49()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_TerminoLogico_342_21_50()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_LlamadaFuncion_531_5_36()
 {
    if (jj_scan_token(ID_VARIABLE)) return true;
    if (jj_scan_token(PAREN_ABRE)) return true;
    return false;
  }

  static private boolean jj_3R_ExpLogica_337_5_40()
 {
    if (jj_3R_TerminoLogico_342_5_45()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_ExpLogica_337_21_46()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Valor_332_5_33()
 {
    if (jj_3R_ExpLogica_337_5_40()) return true;
    return false;
  }

  static private boolean jj_3_10()
 {
    if (jj_3R_ListaSentencias_243_5_13()) return true;
    return false;
  }

  static private boolean jj_3R_OperadorAsignacion_318_5_20()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(53)) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) {
    jj_scanpos = xsp;
    if (jj_scan_token(43)) {
    jj_scanpos = xsp;
    if (jj_scan_token(44)) {
    jj_scanpos = xsp;
    if (jj_scan_token(40)) {
    jj_scanpos = xsp;
    if (jj_scan_token(41)) return true;
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_Asignacion_313_5_8()
 {
    if (jj_scan_token(ID_VARIABLE)) return true;
    if (jj_3R_OperadorAsignacion_318_5_20()) return true;
    return false;
  }

  static private boolean jj_3R_SentenciasSaltos_501_5_38()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(16)) {
    jj_scanpos = xsp;
    if (jj_scan_token(17)) return true;
    }
    if (jj_scan_token(DELIMITADOR)) return true;
    return false;
  }

  static private boolean jj_3R_ListaIdsVariables_308_5_32()
 {
    if (jj_scan_token(ID_VARIABLE)) return true;
    return false;
  }

  static private boolean jj_3R_Declaracion_302_9_25()
 {
    if (jj_3R_ListaIdsVariables_308_5_32()) return true;
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_scan_token(ID_VARIABLE)) return true;
    if (jj_scan_token(ASIGNACION)) return true;
    return false;
  }

  static private boolean jj_3R_HacerMientras_495_5_57()
 {
    if (jj_scan_token(HACER)) return true;
    if (jj_scan_token(LLAVE_ABRE)) return true;
    return false;
  }

  static private boolean jj_3R_Declaracion_298_5_17()
 {
    if (jj_scan_token(VARIABLE)) return true;
    if (jj_3R_TipoDato_292_5_24()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3R_Declaracion_302_9_25()) return true;
    }
    return false;
  }

  static private boolean jj_3R_Mientras_489_5_56()
 {
    if (jj_scan_token(MIENTRAS)) return true;
    if (jj_scan_token(PAREN_ABRE)) return true;
    return false;
  }

  static private boolean jj_3R_Declaracion_297_5_16()
 {
    if (jj_scan_token(CONSTANTE)) return true;
    if (jj_3R_TipoDato_292_5_24()) return true;
    if (jj_scan_token(ID_CONSTANTE)) return true;
    return false;
  }

  static private boolean jj_3R_Declaracion_297_5_6()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Declaracion_297_5_16()) {
    jj_scanpos = xsp;
    if (jj_3R_Declaracion_298_5_17()) return true;
    }
    return false;
  }

  static private boolean jj_3R_TipoDato_292_5_24()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(26)) {
    jj_scanpos = xsp;
    if (jj_scan_token(27)) {
    jj_scanpos = xsp;
    if (jj_scan_token(28)) {
    jj_scanpos = xsp;
    if (jj_scan_token(29)) {
    jj_scanpos = xsp;
    if (jj_scan_token(30)) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_OrfandadSino_275_9_44()
 {
    if (jj_scan_token(SINO)) return true;
    if (jj_scan_token(LLAVE_ABRE)) return true;
    return false;
  }

  static private boolean jj_3R_OrfandadSino_273_9_43()
 {
    if (jj_scan_token(SINO_SI)) return true;
    if (jj_scan_token(PAREN_ABRE)) return true;
    return false;
  }

  static private boolean jj_3R_OrfandadSino_272_5_39()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_OrfandadSino_273_9_43()) {
    jj_scanpos = xsp;
    if (jj_3R_OrfandadSino_275_9_44()) return true;
    }
    return false;
  }

  static private boolean jj_3R_Para_460_5_58()
 {
    if (jj_scan_token(PARA)) return true;
    if (jj_scan_token(PAREN_ABRE)) return true;
    return false;
  }

  static private boolean jj_3R_Sentencia_262_9_31()
 {
    if (jj_3R_OrfandadSino_272_5_39()) return true;
    return false;
  }

  static private boolean jj_3R_Sentencia_261_9_30()
 {
    if (jj_3R_SentenciasSaltos_501_5_38()) return true;
    return false;
  }

  static private boolean jj_3R_Sentencia_260_9_29()
 {
    if (jj_3R_Imprimir_550_5_37()) return true;
    return false;
  }

  static private boolean jj_3R_Ciclos_455_5_53()
 {
    if (jj_3R_Para_460_5_58()) return true;
    return false;
  }

  static private boolean jj_3R_Sentencia_259_9_28()
 {
    if (jj_3R_LlamadaFuncion_531_5_36()) return true;
    return false;
  }

  static private boolean jj_3R_Ciclos_454_5_52()
 {
    if (jj_3R_HacerMientras_495_5_57()) return true;
    return false;
  }

  static private boolean jj_3R_Sentencia_258_9_27()
 {
    if (jj_3R_EstructuraControl_409_5_35()) return true;
    return false;
  }

  static private boolean jj_3R_Ciclos_453_5_48()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Ciclos_453_5_51()) {
    jj_scanpos = xsp;
    if (jj_3R_Ciclos_454_5_52()) {
    jj_scanpos = xsp;
    if (jj_3R_Ciclos_455_5_53()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_Ciclos_453_5_51()
 {
    if (jj_3R_Mientras_489_5_56()) return true;
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_3R_Asignacion_313_5_8()) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_3R_AsignacionArregloMatriz_591_5_7()) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_Declaracion_297_5_6()) return true;
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_DeclaracionArregloMatriz_564_5_5()) return true;
    return false;
  }

  static private boolean jj_3R_AsignacionArregloMatriz_591_50_19()
 {
    if (jj_3R_AccesoArreglo_580_5_10()) return true;
    return false;
  }

  static private boolean jj_3R_Sentencia_253_5_23()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_1()) {
    jj_scanpos = xsp;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_Sentencia_258_9_27()) {
    jj_scanpos = xsp;
    if (jj_3R_Sentencia_259_9_28()) {
    jj_scanpos = xsp;
    if (jj_3R_Sentencia_260_9_29()) {
    jj_scanpos = xsp;
    if (jj_3R_Sentencia_261_9_30()) {
    jj_scanpos = xsp;
    if (jj_3R_Sentencia_262_9_31()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_ListaSentencias_243_5_13()
 {
    if (jj_3R_Sentencia_253_5_23()) return true;
    return false;
  }

  static private boolean jj_3R_ListaSinoSi_432_5_12()
 {
    if (jj_scan_token(SINO_SI)) return true;
    if (jj_scan_token(PAREN_ABRE)) return true;
    return false;
  }

  static private boolean jj_3_9()
 {
    if (jj_3R_ListaSinoSi_432_5_12()) return true;
    return false;
  }

  static private boolean jj_3R_Condicionales_419_5_47()
 {
    if (jj_scan_token(SI)) return true;
    if (jj_scan_token(PAREN_ABRE)) return true;
    return false;
  }

  static private boolean jj_3_11()
 {
    if (jj_3R_AccesoMatriz_585_5_9()) return true;
    return false;
  }

  static private boolean jj_3R_EstructuraControl_410_5_42()
 {
    if (jj_3R_Ciclos_453_5_48()) return true;
    return false;
  }

  static private boolean jj_3R_EstructuraControl_409_5_35()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_EstructuraControl_409_5_41()) {
    jj_scanpos = xsp;
    if (jj_3R_EstructuraControl_410_5_42()) return true;
    }
    return false;
  }

  static private boolean jj_3R_EstructuraControl_409_5_41()
 {
    if (jj_3R_Condicionales_419_5_47()) return true;
    return false;
  }

  static private boolean jj_3R_Indice_597_5_21()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(73)) {
    jj_scanpos = xsp;
    if (jj_scan_token(62)) return true;
    }
    return false;
  }

  static private boolean jj_3R_AsignacionArregloMatriz_591_7_18()
 {
    if (jj_3R_AccesoMatriz_585_5_9()) return true;
    return false;
  }

  static private boolean jj_3R_AsignacionArregloMatriz_591_5_7()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_AsignacionArregloMatriz_591_7_18()) {
    jj_scanpos = xsp;
    if (jj_3R_AsignacionArregloMatriz_591_50_19()) return true;
    }
    return false;
  }

  static private boolean jj_3R_ValorVariable_396_5_75()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(73)) {
    jj_scanpos = xsp;
    if (jj_scan_token(71)) {
    jj_scanpos = xsp;
    if (jj_scan_token(72)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) {
    jj_scanpos = xsp;
    if (jj_scan_token(23)) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_8()
 {
    if (jj_3R_LlamadaFuncionInterna_536_5_11()) return true;
    return false;
  }

  static private boolean jj_3_7()
 {
    if (jj_3R_AccesoArreglo_580_5_10()) return true;
    return false;
  }

  static private boolean jj_3_6()
 {
    if (jj_3R_AccesoMatriz_585_5_9()) return true;
    return false;
  }

  static private boolean jj_3R_AccesoMatriz_585_5_9()
 {
    if (jj_scan_token(ID_VARIABLE)) return true;
    if (jj_scan_token(CORCHETE_ABRE)) return true;
    if (jj_3R_Indice_597_5_21()) return true;
    if (jj_scan_token(CORCHETE_CIERRA)) return true;
    if (jj_scan_token(CORCHETE_ABRE)) return true;
    if (jj_3R_Indice_597_5_21()) return true;
    if (jj_scan_token(CORCHETE_CIERRA)) return true;
    return false;
  }

  static private boolean jj_3R_Atomo_391_5_74()
 {
    if (jj_scan_token(PAREN_ABRE)) return true;
    if (jj_3R_ExpAritmetica_369_5_60()) return true;
    if (jj_scan_token(PAREN_CIERRA)) return true;
    return false;
  }

  static private boolean jj_3R_Atomo_390_5_73()
 {
    if (jj_3R_Leer_555_5_76()) return true;
    return false;
  }

  static private boolean jj_3R_ExpAritmetica_369_26_63()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(47)) {
    jj_scanpos = xsp;
    if (jj_scan_token(48)) return true;
    }
    if (jj_3R_TerminoAritmetico_374_5_62()) return true;
    return false;
  }

  static private boolean jj_3R_Atomo_389_5_72()
 {
    if (jj_3R_ValorVariable_396_5_75()) return true;
    return false;
  }

  static private boolean jj_3R_AccesoArreglo_580_5_10()
 {
    if (jj_scan_token(ID_VARIABLE)) return true;
    if (jj_scan_token(CORCHETE_ABRE)) return true;
    if (jj_3R_Indice_597_5_21()) return true;
    if (jj_scan_token(CORCHETE_CIERRA)) return true;
    return false;
  }

  static private boolean jj_3R_Potencia_379_14_68()
 {
    if (jj_scan_token(POTENCIA)) return true;
    if (jj_3R_Potencia_379_5_65()) return true;
    return false;
  }

  static private boolean jj_3R_Atomo_386_5_71()
 {
    if (jj_3R_LlamadaFuncionInterna_536_5_11()) return true;
    return false;
  }

  static private boolean jj_3R_TerminoAritmetico_374_17_66()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(49)) {
    jj_scanpos = xsp;
    if (jj_scan_token(50)) {
    jj_scanpos = xsp;
    if (jj_scan_token(51)) return true;
    }
    }
    if (jj_3R_Potencia_379_5_65()) return true;
    return false;
  }

  static private boolean jj_3R_Atomo_385_5_70()
 {
    if (jj_3R_AccesoArreglo_580_5_10()) return true;
    return false;
  }

  static private boolean jj_3R_Atomo_384_5_69()
 {
    if (jj_3R_AccesoMatriz_585_5_9()) return true;
    return false;
  }

  static private boolean jj_3R_Atomo_384_5_67()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Atomo_384_5_69()) {
    jj_scanpos = xsp;
    if (jj_3R_Atomo_385_5_70()) {
    jj_scanpos = xsp;
    if (jj_3R_Atomo_386_5_71()) {
    jj_scanpos = xsp;
    if (jj_scan_token(62)) {
    jj_scanpos = xsp;
    if (jj_scan_token(63)) {
    jj_scanpos = xsp;
    if (jj_3R_Atomo_389_5_72()) {
    jj_scanpos = xsp;
    if (jj_3R_Atomo_390_5_73()) {
    jj_scanpos = xsp;
    if (jj_3R_Atomo_391_5_74()) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_DeclaracionArregloMatriz_570_9_15()
 {
    if (jj_scan_token(MATRIX)) return true;
    if (jj_3R_TipoDato_292_5_24()) return true;
    return false;
  }

  static private boolean jj_3R_Potencia_379_5_65()
 {
    if (jj_3R_Atomo_384_5_67()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Potencia_379_14_68()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_DeclaracionArregloMatriz_566_9_14()
 {
    if (jj_scan_token(ARREGLO)) return true;
    if (jj_3R_TipoDato_292_5_24()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public HeroaTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[46];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x40000,0x133fc00,0x40000,0x103fc00,0x1800,0x7c000000,0x0,0x300000,0x0,0x0,0x0,0x0,0x2c00000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x2c00000,0xc00000,0xe400,0x1800,0x800,0x800,0x1000,0xe000,0x0,0x30000,0x7c000000,0x0,0x80000,0x2c00000,0x2c00000,0x2c00000,0x0,0x2c00000,0x0,0x0,0x0,0x80000000,0x0,0x0,0x0,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x40000000,0x0,0x40000000,0x0,0x0,0x40000000,0x0,0x8000000,0x201f00,0x8,0x4,0xc1100000,0x60f0,0x60f0,0x18000,0x18000,0xe0000,0xe0000,0x2,0xc1000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1f00,0x0,0x0,0x8000000,0x0,0xc1100000,0xc1100000,0xc1100000,0x8000000,0xc1100000,0x0,0x200000,0x200000,0x1,0x40000000,0x40000000,0x8000000,0x8000000,};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x380,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x380,0x380,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x380,0x380,0x380,0x0,0x380,0x80,0x0,0x0,0x0,0x0,0x200,0x0,0x0,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[11];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Heroa(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Heroa(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new HeroaTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Heroa(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new HeroaTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new HeroaTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Heroa(HeroaTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(HeroaTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[75];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 46; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 75; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 11; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			   case 8: jj_3_9(); break;
			   case 9: jj_3_10(); break;
			   case 10: jj_3_11(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
