/* Generated By:JavaCC: Do not edit this line. HeroaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HeroaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRINCIPAL = 9;
  /** RegularExpression Id. */
  int SI = 10;
  /** RegularExpression Id. */
  int SINO = 11;
  /** RegularExpression Id. */
  int SINO_SI = 12;
  /** RegularExpression Id. */
  int MIENTRAS = 13;
  /** RegularExpression Id. */
  int PARA = 14;
  /** RegularExpression Id. */
  int HACER = 15;
  /** RegularExpression Id. */
  int ROMPER = 16;
  /** RegularExpression Id. */
  int CONTINUAR = 17;
  /** RegularExpression Id. */
  int FUNCION = 18;
  /** RegularExpression Id. */
  int RETORNAR = 19;
  /** RegularExpression Id. */
  int VARIABLE = 20;
  /** RegularExpression Id. */
  int CONSTANTE = 21;
  /** RegularExpression Id. */
  int VERDADERO = 22;
  /** RegularExpression Id. */
  int FALSO = 23;
  /** RegularExpression Id. */
  int IMPRIMIR = 24;
  /** RegularExpression Id. */
  int LEER = 25;
  /** RegularExpression Id. */
  int ENTERO = 26;
  /** RegularExpression Id. */
  int DECIMAL = 27;
  /** RegularExpression Id. */
  int CHAR = 28;
  /** RegularExpression Id. */
  int BOOLEANO = 29;
  /** RegularExpression Id. */
  int CADENA = 30;
  /** RegularExpression Id. */
  int ARREGLO = 31;
  /** RegularExpression Id. */
  int MATRIX = 32;
  /** RegularExpression Id. */
  int POTENCIA = 33;
  /** RegularExpression Id. */
  int AND = 34;
  /** RegularExpression Id. */
  int OR = 35;
  /** RegularExpression Id. */
  int IGUAL_QUE = 36;
  /** RegularExpression Id. */
  int DIFERENTE_DE = 37;
  /** RegularExpression Id. */
  int MAYOR_IGUAL = 38;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 39;
  /** RegularExpression Id. */
  int ASIGNACION_SUMA = 40;
  /** RegularExpression Id. */
  int ASIGNACION_RESTA = 41;
  /** RegularExpression Id. */
  int ASIGNACION_MULTIPLICACION = 42;
  /** RegularExpression Id. */
  int ASIGNACION_DIVISION = 43;
  /** RegularExpression Id. */
  int ASIGNACION_MODULO = 44;
  /** RegularExpression Id. */
  int MAYOR_QUE = 45;
  /** RegularExpression Id. */
  int MENOR_QUE = 46;
  /** RegularExpression Id. */
  int SUMA = 47;
  /** RegularExpression Id. */
  int RESTA = 48;
  /** RegularExpression Id. */
  int MULTIPLICACION = 49;
  /** RegularExpression Id. */
  int DIVISION = 50;
  /** RegularExpression Id. */
  int MODULO = 51;
  /** RegularExpression Id. */
  int NOT = 52;
  /** RegularExpression Id. */
  int ASIGNACION = 53;
  /** RegularExpression Id. */
  int LLAVE_ABRE = 54;
  /** RegularExpression Id. */
  int LLAVE_CIERRA = 55;
  /** RegularExpression Id. */
  int PAREN_ABRE = 56;
  /** RegularExpression Id. */
  int PAREN_CIERRA = 57;
  /** RegularExpression Id. */
  int DELIMITADOR = 58;
  /** RegularExpression Id. */
  int COMA = 59;
  /** RegularExpression Id. */
  int CORCHETE_ABRE = 60;
  /** RegularExpression Id. */
  int CORCHETE_CIERRA = 61;
  /** RegularExpression Id. */
  int ID_VARIABLE = 62;
  /** RegularExpression Id. */
  int ID_CONSTANTE = 63;
  /** RegularExpression Id. */
  int MINUSCULA = 64;
  /** RegularExpression Id. */
  int MAYUSCULA = 65;
  /** RegularExpression Id. */
  int DIGITO = 66;
  /** RegularExpression Id. */
  int LETRA = 67;
  /** RegularExpression Id. */
  int CARACTER = 68;
  /** RegularExpression Id. */
  int RESTO_ID_VARIABLE = 69;
  /** RegularExpression Id. */
  int RESTO_ID_CONSTANTE = 70;
  /** RegularExpression Id. */
  int VALOR_CADENA = 71;
  /** RegularExpression Id. */
  int VALOR_CHAR = 72;
  /** RegularExpression Id. */
  int VALOR_NUMERO = 73;
  /** RegularExpression Id. */
  int ERROR_LEXICO = 74;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTILINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"*\\\\\"",
    "\"\\\\*\"",
    "<token of kind 8>",
    "\"principal\"",
    "\"si\"",
    "\"sino\"",
    "\"sino_si\"",
    "\"mientras\"",
    "\"para\"",
    "\"hacer\"",
    "\"romper\"",
    "\"continuar\"",
    "\"funcion\"",
    "\"retornar\"",
    "\"variable\"",
    "\"constante\"",
    "\"verdadero\"",
    "\"falso\"",
    "\"imprimir\"",
    "\"leer\"",
    "\"entero\"",
    "\"decimal\"",
    "\"caracter\"",
    "\"booleano\"",
    "\"cadena\"",
    "\"arreglo\"",
    "\"matriz\"",
    "\"**\"",
    "\"&&\"",
    "\"|||\"",
    "\"==\"",
    "\"=!\"",
    "\">=\"",
    "\"<=\"",
    "\"=+\"",
    "\"=-\"",
    "\"=*\"",
    "\"=/\"",
    "\"=%\"",
    "\">\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"!\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "<ID_VARIABLE>",
    "<ID_CONSTANTE>",
    "<MINUSCULA>",
    "<MAYUSCULA>",
    "<DIGITO>",
    "<LETRA>",
    "<CARACTER>",
    "<RESTO_ID_VARIABLE>",
    "<RESTO_ID_CONSTANTE>",
    "<VALOR_CADENA>",
    "<VALOR_CHAR>",
    "<VALOR_NUMERO>",
    "<ERROR_LEXICO>",
  };

}
