
PARSER_BEGIN(Heroa)
import java.io.*;

public class Heroa {
    public static void main(String[] args){
      try{
          InputStream input = new FileInputStream("prueba.txt");
          Heroa analizador = new Heroa(input);
          analizador.Programa();
          System.out.println("Análisis Sintáctico terminado con éxito.");
      } catch (FileNotFoundException e){
          System.out.println("Error: El archivo 'prueba.txt' no existe.");
      } catch (ParseException e){
          System.err.println("Error Sintáctico: " + e.getMessage());
      } catch (TokenMgrError e){
          System.err.println("Error Léxico detectado: " + e.getMessage());
      }
    }
}
PARSER_END(Heroa)

SKIP : {
    " "
  | "\r"
  | "\t"
  | "\n"
  | <"\\\\\\" (~["\n", "\r"])* ("\n" | "\r" | "\r\n")?>   // Comentario de línea: \\\
  | "*\\" : IN_MULTILINE_COMMENT                         // Inicio bloque: *\
}

<IN_MULTILINE_COMMENT> SKIP : {
    "\\*" : DEFAULT
  | <~[]>
}

TOKEN :{
    // Palabras reservadas
    <PRINCIPAL: "Principal">  |
    <SI: "si">                |
    <SINO: "sino">            |
    <SINO_SI: "sino_si">      |
    <MIENTRAS: "mientras">    |
    <PARA: "para">            |
    <HACER: "hacer">          |
    <ROMPER: "romper">        |
    <CONTINUAR: "continuar">  |
    <FUNCION: "funcion">      |
    <RETORNAR: "retornar">    |
    <VARIABLE: "variable">    |
    <VERDADERO: "verdadero">  |
    <FALSO: "falso">          |
    <IMPRIMIR: "imprimir">    |
    <LEER: "leer">            |
    // Tipos de dato
    <ENTERO: "entero">     |
    <DECIMAL: "decimal">   |
    <CHAR: "caracter">     |
    <BOOLEANO: "booleano"> |
    <CADENA: "cadena">     |
    // Operadores (los más largos primero)
    <POTENCIA: "**">                  |
    <AND: "&&">                       |
    <OR: "|||">                       |
    <IGUAL_QUE: "==">                 |
    <DIFERENTE_DE: "=!">              |
    <MAYOR_IGUAL: ">=">               |
    <MENOR_IGUAL: "<=">               |
    <ASIGNACION_SUMA: "=+">           |
    <ASIGNACION_RESTA: "=-">          |
    <ASIGNACION_MULTIPLICACION: "=*"> |
    <ASIGNACION_DIVISION: "=/">       |
    <ASIGNACION_MODULO: "=%">         |
    //Operadores Simples
    <MAYOR_QUE: ">">      |
    <MENOR_QUE: "<">      |
    <SUMA: "+">           |
    <RESTA: "-">          |
    <MULTIPLICACION: "*"> |
    <DIVISION: "/">       |
    <MODULO: "%">         |
    <NOT: "!">            |
    <ASIGNACION: "=">     |
    // Puntuacion
    <LLAVE_ABRE: "{">   |
    <LLAVE_CIERRA: "}"> |
    <PAREN_ABRE: "(">   |
    <PAREN_CIERRA: ")"> |
    <DELIMITADOR: ";">  |
    <COMA: ",">         |
    // Identificadores y valores
    <IDENTIFICADOR: <MINUSCULA> (<RESTO_IDENTIFICADOR>)*> |
    <#MINUSCULA: ["a"-"z"]>                               |
    <#MAYUSCULA: ["A"-"Z"]>                               |
    <#DIGITO: ["0"-"9"]>                                  |
    <#LETRA: <MINUSCULA> | <MAYUSCULA>>                   |
    <#CARACTER: <LETRA> | <DIGITO>>                       |
    <#RESTO_IDENTIFICADOR: ("_")? <CARACTER>>             |
    <VALOR_CADENA: "\"" (~["\""])* "\"">                  |
    <VALOR_NUMERO: (["0"-"9"])+ ("." (["0"-"9"])+)?>
}

//Estructura Principal

void Programa():{}
{
    (DefFuncion())* Principal() (DefFuncion())* <EOF>
    {System.out.println("Sintaxis Correcta: Programa completo");}
}

void Principal():{}
{
    <PRINCIPAL> <LLAVE_ABRE> (Sentencia())* <LLAVE_CIERRA>
    {System.out.println("Sintaxis Correcta: Bloque Principal");}
}

void Sentencia(): {}
{
    LOOKAHEAD(3) Declaracion()        |
    LOOKAHEAD(4) AsignacionFuncion()  |
    LOOKAHEAD(2) Asignacion()         |
    Condicional ()                    |
    Ciclo ()                          |
    DefFuncion ()                     |
    LlamadaFuncion()                  |
    Imprimir ()                       |
    Retornar()
}

void Declaracion():{}
{
    <VARIABLE> TipoDato() <IDENTIFICADOR>
    (
        <ASIGNACION> Expresion() <DELIMITADOR>  |
        (<COMA> <IDENTIFICADOR>)+ <DELIMITADOR> |
        <DELIMITADOR>
    )
    {System.out.println("Sintaxis Correcta: Declaracion");}
}

void Asignacion():{}
{
    <IDENTIFICADOR>
    (
        <ASIGNACION>                |
        <ASIGNACION_SUMA>           |
        <ASIGNACION_RESTA>          |
        <ASIGNACION_MULTIPLICACION> |
        <ASIGNACION_DIVISION>       |
        <ASIGNACION_MODULO>
    )
    ExpresionLogica() <DELIMITADOR>
    {System.out.println("Sintaxis Correcta: Asignacion detectada");}
}

void Condicional():{}
{
    <SI> <PAREN_ABRE> ExpresionLogica() <PAREN_CIERRA>
    <LLAVE_ABRE> (Sentencia())* <LLAVE_CIERRA>
    {System.out.println("Sintaxis Correcta: Bloque SI");}
    (
        LOOKAHEAD(2) <SINO_SI> <PAREN_ABRE> ExpresionLogica() <PAREN_CIERRA>
        <LLAVE_ABRE> (Sentencia())* <LLAVE_CIERRA>
        {System.out.println("Sintaxis Correcta: Bloque SINO SI");}
    )*
    (
        LOOKAHEAD(1) <SINO>
        <LLAVE_ABRE> (Sentencia())* <LLAVE_CIERRA>
        {System.out.println("Sintaxis Correcta: Bloque SINO");}
    )?
}

void Ciclo():{}
{
    Mientras()      |
    HacerMientras() |
    Para()
}

void DefFuncion():{}
{
    <FUNCION> <IDENTIFICADOR> <PAREN_ABRE>
    (ListaParametros())?
    <PAREN_CIERRA>
    <LLAVE_ABRE>
    (Sentencia())*
    <LLAVE_CIERRA>
    {System.out.println("Sintaxis Correcta: Definicion de Funcion");}
}

void LlamadaFuncion():{}
{
    <IDENTIFICADOR> <PAREN_ABRE>
    (ListaArgumentos())?
    <PAREN_CIERRA>
    (
        <DELIMITADOR>
        {System.out.println("Sintaxis Correcta: Llamada a Funcion");}
    )
}

void Imprimir():{}
{
    <IMPRIMIR> <PAREN_ABRE>
    (ExpresionLogica())?
    <PAREN_CIERRA> <DELIMITADOR>
    {System.out.println("Sintaxis Correcta: Sentencia Imprimir");}
}

void Retornar():{}
{
    <RETORNAR>
    (
        LOOKAHEAD(2)
        ExpresionLogica()
        {System.out.println("Sintaxis Correcta: Retornar con Valor");}
    )?
    {System.out.println("Sintaxis Correcta: Retorno Simple");}
    <DELIMITADOR>
}

//Reglas de la Estructura Principal

void TipoDato():{}
{
    <ENTERO> | <DECIMAL> | <BOOLEANO> | <CADENA> | <CHAR>
}

void Expresion():{}
{
    ExpresionLogica()
}

void ExpresionLogica():{}
{
    ExpresionRelacional() ((<AND> | <OR>)ExpresionRelacional())*
}

void ExpresionRelacional(): {}
{
    ExpresionAritmetica() ((<IGUAL_QUE> | <DIFERENTE_DE> | <MAYOR_QUE> |<MENOR_QUE> | <MAYOR_IGUAL> | <MENOR_IGUAL> ) ExpresionAritmetica())?
}

void ExpresionAritmetica():{}
{
    Termino() ((<SUMA> | <RESTA> ) Termino())*
}

void Termino():{}
{
    Potencia() ((<MULTIPLICACION> | <DIVISION> | <MODULO> ) Potencia())*
}

void Potencia():{}
{
    Factor() (<POTENCIA> Factor())*
}

void Factor():{} {
    LOOKAHEAD(2) LlamadaFuncionAsignacion()       |
    <NOT> Factor()                                |
    <PAREN_ABRE> ExpresionLogica() <PAREN_CIERRA> |
    <VALOR_NUMERO>                                |
    <VALOR_CADENA>                                |
    <VERDADERO>                                   |
    <FALSO>                                       |
    <IDENTIFICADOR>                               |
    <LEER> <PAREN_ABRE> (<VALOR_CADENA>)? <PAREN_CIERRA>
}

void Mientras(): {}
{
    <MIENTRAS> <PAREN_ABRE> ExpresionLogica() <PAREN_CIERRA>
    <LLAVE_ABRE> (Sentencia())* <LLAVE_CIERRA>
    {System.out.println("Sintaxis Correcta: Ciclo MIENTRAS");}
}

void HacerMientras():{}
{
    <HACER> <LLAVE_ABRE> (Sentencia())*<LLAVE_CIERRA>
    <MIENTRAS> <PAREN_ABRE> ExpresionLogica() <PAREN_CIERRA> <DELIMITADOR>
    {System.out.println("Sintaxis Correcta: Ciclo HACER - MIENTRAS");}
}

void Para():{}
{
    <PARA> <PAREN_ABRE>
        InicioPara() <DELIMITADOR>
        ExpresionLogica() <DELIMITADOR>
        ActualizacionPara()
    <PAREN_CIERRA>
    <LLAVE_ABRE> (Sentencia())* <LLAVE_CIERRA>
    {System.out.println("Sintaxis Correcta: Ciclo PARA");}
}

void InicioPara():{}
{
    LOOKAHEAD(3) DeclaracionPara() | AsignacionPara()
}

void DeclaracionPara():{}
{
    <VARIABLE> TipoDato() <IDENTIFICADOR> <ASIGNACION> ExpresionAritmetica()
}

void AsignacionPara():{}
{
    <IDENTIFICADOR> <ASIGNACION> ExpresionAritmetica()
}

void ActualizacionPara():{}
{
    <IDENTIFICADOR>
    (
        <ASIGNACION_SUMA>           |
        <ASIGNACION_RESTA>          |
        <ASIGNACION_MULTIPLICACION> |
        <ASIGNACION_DIVISION>       |
        <ASIGNACION_MODULO>         |
        <ASIGNACION>
    )
    ExpresionAritmetica()
}

void ListaArgumentos():{}
{
    Argumento() (<COMA> Argumento())*
}

void Argumento(): {}
{
    ExpresionLogica()
}

void ListaParametros():{}
{
    Parametro() (<COMA> Parametro())*
}

void Parametro(): {}
{
    TipoDato() <IDENTIFICADOR>
}

void AsignacionFuncion():{} {
    <IDENTIFICADOR> <ASIGNACION> LlamadaFuncionAsignacion() <DELIMITADOR>
    {System.out.println("Sintaxis Correcta: Asignacion de Funcion");}
}

void LlamadaFuncionAsignacion():{}
{
    <IDENTIFICADOR> <PAREN_ABRE> (ListaArgumentos())? <PAREN_CIERRA>
}
